### ISSUE TITLE
The Gtk.jl dependency opens an extra icon in the dock on Mac

### ISSUE THREAD

**Issue by davidanthoff** [lobingera/Rsvg.jl#15]
A simple ``using Rsvg`` from a julia REPL on Mac opens up an extra icon on the Mac dock, which seems not ideal. This is actually caused by ``using Gtk``, which already opens that extra icon.

I'm not sure how one could work around this, but it seems not ideal. I guess one question is whether Rsvg.jl really needs a dependency on a full window toolkit? Might there be some way to get rid of that dependency? Or some other idea?

We are using Rsvg.jl in VegaLite.jl to implement all sorts of file export features, and it works great. But it is weird that if someone does ``using VegLite``, that a new icon pops up on Macs.

**Comment by lobingera** [comment]
Looks like the real problem is in Gtk.jl, not in using it ...
The Gtk dependency was the simplest (and i think even still today the only) way to access glib which is used by librsvg for error reporting. I see two possible solutions: 
* Introduce a Glib.jl package by splitting off from Gtk to used in situations like this 
* Do a local, 'small' library adaptation of glib only for the GError https://developer.gnome.org/glib/stable/glib-Error-Reporting.html#GError
