### ISSUE TITLE
Error with g_error_free

### ISSUE THREAD

**Issue by davidanthoff** [lobingera/Rsvg.jl#38]
Just ran into the following error on `master` on Windows:
```
  Got exception outside of a @test
  ccall: could not find function g_error_free in library C:\Users\david\.julia\packages\Rsvg\0R8IA\deps\usr\bin\librsvg-2-2.dll
  Stacktrace:
   [1] handle_new_from_data(::String) at C:\Users\david\.julia\packages\Rsvg\0R8IA\src\calls.jl:111
```
@giordano, any idea?

I think that means we should probably hold off from tagging a release...

**Comment by giordano** [comment]
Where is the `g_error_free` function defined?

**Comment by giordano** [comment]
I don't have access to a Windows machine, so I'm testing on my GNU/Linux box.  In `Rsvg/deps/usr/lib`:
```sh
% for file in *.so; do nm -D $file | grep g_error_free && echo "symbol found in $file"; done
                 U g_error_free
symbol found in libgdk_pixbuf-2.0.so
                 U g_error_free
symbol found in libgio-2.0.so
0000000000037a40 T g_error_free
symbol found in libglib-2.0.so
                 U g_error_free
symbol found in libgobject-2.0.so
                 U g_error_free
symbol found in libpango-1.0.so
                 U g_error_free
symbol found in librsvg-2.so
```
So the symbol is only in `libglib`.  It's undefined in `librsvg`, relying on linking to libglib.  It would be interesting to understand why it's not being loaded, but as a workaround you might be able to call the function from `libglib` instead of `librsvg`.

Could you please run
```julia
using Rsvg, Libdl
println(dllist())
```
in your session?

**Comment by davidanthoff** [comment]
Ok, actually, the same error happens on previous versions, so this is unrelated to our recent move to BinaryProvider.jl. So I think this should _not_ block tagging a new release, I think this can be fixed later.

I'm pretty sure that this piece of code was just never properly tested, and we just need to make sure we call the function from `libglib`.
